feat: add support to display examples
asyncapi/avro-schema-parser pull request #53
Opened 2021-05-07 20:33 UTC by ITman1

**Description**

- When `example` attribute is specified alongside with type/record field definition it is propagated into `examples` attribute of AsyncAPI schema 
- Tested locally and on REACT component playground

![image](https://user-images.githubusercontent.com/1372054/117513650-7486a800-af92-11eb-9956-fd1983978c4b.png)

**Related issue(s)**
Implements `example` feature from https://github.com/asyncapi/avro-schema-parser/issues/18

2021-07-26 19:53 UTC, derberg commented
@ITman1 please update with latest master

2021-07-27 14:27 UTC, ITman1 commented
@derberg Updated from upstream repo

2021-07-29 15:33 UTC, bpb54321 commented
When will this be merged? I would like to use this ASAP in my project.

2021-07-29 18:42 UTC, derberg commented
@bpb54321 I want to wait at least until the end of the week. Maybe @iemejia called out by @ITman1 will have time to have a look and will share his opinion on this. Otherwise next week definitely.

2021-07-29 18:42 UTC, derberg commented
@ITman1 please have a look at failing linter, it complains on the complexity of the code

2021-08-01 15:45 UTC, ITman1 commented
@derberg Tried to extract some code into seperate functions, Sonar does not complain anymore locally. Both tests started to fail after my change so I also adjusted expected test results. IMHO there was a bug, Avro can have 'null' as default values, before null was ignored from the spec files and so does also 0 I would guess.

2021-08-03 12:23 UTC, derberg requested changes
one tiny request to add one additional comment to the code + please update readme with information of extra fields support

2021-08-03 12:23 UTC, derberg commented on to-json-schema.js
> +      const defType = avroDef.type || avroDef;
```suggestion
      // avroDef can be { type: 'int', default: 1 } and this is why avroDef.type has priority here
      const defType = avroDef.type || avroDef;
```

sorry but I need such comments in code as it is hard to maintain such project overtime, where changes are done very rarely

2021-08-13 12:40 UTC, M3lkior commented
> @ITman1 fyi, I asked the community to share their opinion on a related issue as I'm not sure if we should actually provide such a support

From my side, it could be nice to have this feature merged. Here is the result of my generation based on `avsc` files ; all the attributes are null ; handle the `example` attribute could improve the reader experience ;)

![image](https://user-images.githubusercontent.com/5501911/129358491-d1553495-df40-4fbd-af9c-14e0ebcced2b.png)

2021-08-16 06:43 UTC, derberg approved these changes

2021-08-16 06:44 UTC, derberg commented
@ITman1 hey, sorry I did not notice you made required changes, if @M3lkior would not add his comment, I would miss it. There are too many PRs in many different repos. Next time you contribute (I hope you will 😄 ) please use the button to `re-request` review to trigger a notification.

2021-08-16 06:45 UTC, merged